import { by, element } from 'protractor';
export const Home = {

    Login: element(by.cssContainingText('span.mat-button-wrapper', 'Log In')),
    UserName: element(by.id('username')),
    Password: element(by.id('password')),
    LoginContinue: element(by.cssContainingText('button', 'Continue')),
    ForgotPassword: element(by.cssContainingText('p.c66aeac53.c1eb4fc59', 'Forgot password?')),
    WelcomeText: element(by.css('h2')),
    LoginError: element(by.css('li.cc58a9ba3')),
    EmailError: element(by.css('ul.cf754da02')),
    BackToFT :  element(by.cssContainingText('a','Back to FastTrack')),
    Logout: element(by.cssContainingText('span.mat-button-wrapper', ' Log Out ')),
    Home: element(by.cssContainingText('div.nav-item.landing', ' Home')),
    HomeSelected: element(by.cssContainingText('div.nav-item.landing.selected', ' Home')),
    HomeActivities: element(by.cssContainingText('h4.task-list-title', 'Activities')),
    MyDogs: element(by.cssContainingText('div.nav-item mydogs', ' My Dogs')),
    MyDogsSelected: element(by.cssContainingText('div.nav-item mydogs.selected', ' My Dogs')),
    NonRacing: element(by.cssContainingText('a.mat-tab-link.mat-focus-indicator.ng-star-inserted', ' Non Racing Dogs ')),
    Breeding: element(by.cssContainingText('a.mat-tab-label-active', ' Breeding & Litters ')),
    BlackBook: element(by.cssContainingText('a.mat-tab-label-active', ' Blackbook ')),
    Racing: element(by.cssContainingText('a.mat-tab-label-active', ' Racing Dogs ')),
    Dog: element(by.css('app-dog-card:nth-child(1)')).element(by.css('app-dog-card-header')).element(by.css('div.right')).element(by.css('button')).element(by.css('span.mat-button-wrapper')).element(by.css('mat-icon')),

    GotIt: element(by.cssContainingText('button.next-button.shepherd-button ', 'Got it!')),
    Gotit2: element(by.xpath("/html/body/div[3]/div[2]/footer/button[2]")),
    Gotit3: element(by.xpath("/html/body/div[4]/div[2]/footer/button[2]")),
    Gotit4: element(by.xpath("/html/body/div[5]/div[2]/footer/button[2]")),
    Gotit5: element(by.xpath("/html/body/div[6]/div[2]/footer/button[2]")),
    SkipOverlay: element(by.cssContainingText('button.cancel-button.shepherd-button.shepherd-button-secondary', 'Done? Click here to skip')),

    Home1Menu: element(by.id('landing-menu-label')),
    Home1Description: element(by.id('landing-menu-description')),
    Home2Description: element(by.id('landing-activities-description')),
    Home2Menu: element(by.id('landing-activities-label')),
    Home3Menu: element(by.id('landing-announcements-label')),
    Home3Description: element(by.id('landing-announcements-description')),
    Home4Menu: element(by.id('landing-meeting-updates-label')),
    Home4Description: element(by.id('landing-meeting-updates-description')),
    Home5Menu: element(by.id('landing-search-label')),
    Home5Description: element(by.id('landing-search-description')),

    MyDogs1Menu: element(by.id('mydogs-tabs-label')),
    MyDogs1Description: element(by.id('mydogs-tabs-description')),
    MyDogs2Menu: element(by.id('mydogs-sort-label')),
    MyDogs2Description: element(by.id('mydogs-sort-description')),
    MyDogs3Menu: element(by.id('mydogs-filter-label')),
    MyDogs3Description: element(by.id('mydogs-filter-description')),
    MyDogs4Menu: element(by.id('mydogs-card-label')),
    MyDogs4Description: element(by.id('mydogs-card-description')),
    MyDogs5Menu: element(by.id('mydogs-actions-label')),
    MyDogs5Description: element(by.id('mydogs-actions-description')),
    
};
