import { by, element } from 'protractor';
import { spawn } from 'child_process';
export const RetireGreyhound = {
DogEarbrand: element.all(by.css('app-dog-ear-brand')),
RetirementStatusDropdown: element(by.css('span.selected-value-button.ng-star-inserted')),
RetirementStatusList: element.all(by.css('mat-button-toggle-group')),
SelectPet: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Pet')),
SelectBreedingAnimal: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Breeding Animal')),
SelectEuthanised: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Euthanised')),
SelectExported: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Exported')),
SelectOther: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Other')),
RetiredToOwner: element(by.cssContainingText('div.mat-radio-label-content', 'Owner')),
RetiredToThirdParty: element(by.cssContainingText('div.mat-radio-label-content', 'A Third Party')),
RetiredDate:  element(by.css('button.mat-focus-indicator.mat-icon-button.mat-button-base')),
SelectRetiredDate: element(by.css('td.mat-calendar-body-cell.mat-calendar-body-active.ng-star-inserted')),
EnterFirstName: element(by.xpath("//input[@id='mat-input-2']")),
EnterLastName: element(by.xpath("//input[@id='mat-input-3']")),
EnterContact: element(by.xpath("//input[@id='mat-input-4']")),
EnterEmail: element(by.xpath("//input[@id='mat-input-5']")),
EnterStreet: element(by.xpath("//input[@id='mat-input-8']")),
EnterSuburb: element(by.xpath("//input[@id='mat-input-9']")),
SelectStateDropDown:  element(by.cssContainingText('span', 'State')),
EnterState: element(by.cssContainingText('span.mat-option-text', ' New South Wales ')),
EnterPostcode: element(by.xpath("//input[@id='mat-input-10']")),
EnterAlternateName: element(by.id('mat-input-6')),
EnterAlternateNo: element(by.id('mat-input-7')),
SameAsPhysicalAdd:  element(by.cssContainingText('span.mat-checkbox-label','same as physical address')),
DisposalMethod: element(by.cssContainingText('strong.ng-star-inserted', 'Disposal Method:')),
SelectDisposalMethodVet: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Veterinary Clinic')),
SelectDisposalMethodAnimalCremation: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Animal Cremation Service')),
SelectMethodOther: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Other')),
ReasonOfEuthanasia: element(by.cssContainingText('strong.ng-star-inserted', 'Reason for Euthanasia:')),
SelectReasonOfEuthanasiaInjury: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Due to Injury')),
SelectReasonOfEuthanasiaEmergency: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Emergency')),
SelectReasonOfEuthanasiaLackOfAbility: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Lack of Ability')),
SelectReasonOfEuthanasiaNotRehoming: element(by.cssContainingText('div.mat-button-toggle-label-content', 'Unsuitable For Re-Homing')),
VetName: element(by.id('mat-input-1')),
DateContactedForVet: element(by.id('mat-input-2')),
TimeContactedForVet: element(by.id('mat-input-3')),
EnterDetails: element(by.id('mat-input-4')),
EnterDisposalAsOther: element(by.id('mat-input-1')),
PassportNo: element(by.id('mat-input-2')),
DestinationCountry: element(by.id('mat-input-3')),
Agree: element(by.cssContainingText('span.mat-checkbox-label', 'You Agree')),
EnterOtherOtherDetails: element(by.id('mat-input-2'))
}